"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "es" | "pt";

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    toggleLanguage: () => void;
    t: (key: string) => string;
    userName: string;
    setUserName: (name: string) => void;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const dictionaries = {
    en: {
        "nav.home": "Home",
        "nav.tourism": "Active Tourism",
        "nav.parks": "Parks",
        "nav.swimming": "Swimming",
        "nav.cycling": "Cycling",
        "nav.mental": "Mental Health",
        "nav.women": "Women's Health",
        "nav.procedures": "Procedures",
        "nav.community": "Community",
        "nav.vault": "My Vault",
        "nav.achievements": "Achievements",
        "nav.socialFit": "Social Fitness",
        "nav.sportsTeams": "Sports Teams",
        "nav.recipes": "Taste of Home",
        "nav.more": "More",
        "nav.physical_activity": "Physical",
        "nav.health": "Health",
        "nav.admin": "Resources",
        "nav.physiotherapy": "Physio",
        "nav.calculator": "Calculator",
        "nav.jobs": "Jobs & Careers",
        "nav.slang": "Speak like a Local",
        "nav.active": "Active Tourism",
        "nav.toolkit": "Toolkit",
        "toolkit.title": "Essentials Hub",
        "toolkit.subtitle": "Essential tools for your life in Dublin.",
        "tool.vault.desc": "Private storage for your immigration deadlines and documents.",
        "tool.budgeter.desc": "Plan your finances with real local averages for Dublin.",
        "tool.career.desc": "Guides for finding work, CV tips, and recruitment in Ireland.",
        "tool.slang.desc": "Learn essential Irish slang to sound like a native.",
        "tool.achievements.desc": "Track your progress and earn badges as you explore.",
        "tool.community.desc": "Connect with other migrants, join forums, and find events.",
        "tool.recipes.desc": "Community recipe book to cook your favorite Latin dishes.",
        "tool.open": "Open Tool",
        "nav.budgeter": "Budgeter",
        "nav.career": "Career Hub",
        "btn.visit": "Visit Official Website",
        "lbl.backTo": "Back to",
        "lbl.gettingThere": "Getting There",
        "lbl.highlights": "Highlights",
        "lbl.offices": "Office Locations",
        "lbl.expiry": "Expiry Date",
        "lbl.reminder": "Renewal Reminder",
        "lbl.completeRoute": "Mark as Completed",
        "lbl.completed": "Completed!",
        "lbl.badges": "Badges",
        "lbl.trainWithMe": "Train With Me",
        "lbl.collectiveGoal": "Collective Goal",
        "hero.greeting": "G'day,",
        "hero.subtitle": "Ready to explore?",
        "challenge.title": "Daily Challenge",
        "challenge.name": "Nature Walk & Reflection",
        "challenge.desc": "Find a quiet spot in St. Stephen's Green and spend 10 minutes observing the locals.",
        "btn.startNow": "Start Now",
        "common.viewAll": "View all",
        "cat.body": "Body",
        "cat.explore": "Explore",
        "cat.wellness": "Wellness",
        "cat.social": "Social",
        "cat.admin": "Admin",
        "cat.extras": "Extras",
        "home.quickAccess": "Quick Access",
        "nav.lang": "Language",
        "nav.lang_name": "English",
        "nav.lang_toggle": "Português",
        "event.title": "Upcoming Events",
        "event.subtitle": "Free and community-focused meetups.",
        "event.free": "Free Entry",
        "event.viewFull": "View Full Calendar",
        "forum.title": "Community Forum",
        "forum.subtitle": "Ask questions, share tips.",
        "forum.likes": "Likes",
        "forum.replies": "Replies",
        "forum.placeholder": "Ask something...",
        "weather.good": "Perfect for a walk",
        "weather.bad": "Indoor Activity Recommended",
        "weather.clear": "Clear",
        "weather.cloudy": "Partly Cloudy",
        "weather.rain": "Raining",
        "weather.storm": "Thunderstorm",
        "weather.fog": "Foggy",
        "roadmap.title": "Newcomer Roadmap",
        "roadmap.subtitle": "Essential steps for your first weeks",
        "search.placeholder": "Search Dublin resources...",
        "search.popular": "Popular Keywords",
        "search.results": "Results",
        "search.noResults": "No results found...",
        "exercise.title": "Universal Fitness",
        "exercise.subtitle": "Adaptive routes and activities for everyone. Choose a category to start exploring.",
        "exercise.cat.parks.title": "Park Walking Circuits",
        "exercise.cat.parks.desc": "Directory of walking routes in Dublin's best parks (Phoenix, St. Anne's, Fairview, etc.).",
        "exercise.cat.swimming.title": "Open Water Swimming",
        "exercise.cat.swimming.desc": "Directory of sea swimming spots (Seapoint, Forty Foot, Vico, etc.).",
        "exercise.cat.cycling.title": "Cycling Routes",
        "exercise.cat.cycling.desc": "Safe cycle lanes and greenways (Clontarf, Phoenix Park, Canals).",
        "exercise.cat.gyms.title": "Public Gyms & Pools",
        "exercise.cat.gyms.desc": "Affordable, high-quality leisure centers run by Dublin City Council.",
        "exercise.cat.physio.title": "Physiotherapy & Recovery",
        "exercise.cat.physio.desc": "Find community physiotherapists and clinics.",
        "exercise.cat.run.title": "Dublin Bay Coastal Run",
        "exercise.cat.run.desc": "5km scenic route along the coast. Enjoy the sea breeze and flat terrain.",
        "exercise.cat.walk.title": "Liffey River Walk",
        "exercise.cat.walk.desc": "A gentle 2km loop along the River Liffey. Perfect for beginners or rehabilitation.",
        "exercise.cat.teams.title": "Community Sports Teams",
        "exercise.cat.teams.desc": "Join free amateur teams for Football, Rugby, or GAA (Gaelic games) in parks like Fairview Park.",
        "comm.title": "Community",
        "comm.subtitle": "The heart of immiGrow. Connect and grow with others.",
        "comm.myStory": "My Story",
        "comm.myStory.desc": "Personalize your profile, tell your story and connect with others.",
        "comm.circles": "Circles",
        "comm.circles.desc": "Support groups for women, Latinos, newcomers, and more.",
        "comm.mentors": "Mentors",
        "comm.mentors.desc": "Connect with experienced migrants who can guide you.",
        "comm.events": "Events",
        "comm.events.desc": "Face-to-face meetings, walks, and coffee to socialize.",
        "comm.socialFit": "Social Fitness",
        "comm.socialFit.desc": "Train with others, join challenges and share achievements.",
        "comm.identity": "Your Identity",
        "comm.namePlaceholder": "Your name or nickname...",
        "vault.subtitle": "Your personal immigration hub. Categories, notes, and reminders for your life in Ireland.",
        "vault.quickNotes": "Quick Copy Notes",
        "vault.addNote": "+ Add Note",
        "vault.saveNote": "Save Note",
        "vault.myDocs": "My Documents",
        "vault.newDoc": "+ New Doc",
        "vault.docName": "Document Name",
        "vault.category": "Category",
        "vault.reminderOn": "Reminder ON",
        "vault.remove": "Remove",
        "vault.createRecord": "Create Record",
        "vault.cat.identity": "Identity",
        "vault.cat.housing": "Housing",
        "vault.cat.health": "Health",
        "vault.cat.work": "Work",
        "vault.content": "Content",
        "vault.label": "Label (e.g. PPSN)",
        "safe.title": "Safety First",
        "safe.disclaimer": "immiGrow is informative. Stay safe!",
        "safe.public": "Public Places",
        "safe.public.desc": "Always meet in busy, well-lit public areas like cafes or main parks.",
        "safe.inform": "Inform Someone",
        "safe.inform.desc": "Let a friend or family member know where you are going and who you are meeting.",
        "safe.privacy": "Protect Privacy",
        "safe.privacy.desc": "Don't share sensitive details like your bank account or home address immediately.",
        "safe.instinct": "Trust Your Instinct",
        "safe.instinct.desc": "If something feels wrong, it's okay to leave or cancel. Your safety comes first.",
        "jobs.title": "Dublin Ready",
        "mental.subtitle": "Resources and support for your emotional well-being.",
        "mental.professionals": "Directory of Professionals",
        "mental.crisis.title": "Need help right now?",
        "mental.crisis.desc": "Confidential 24/7 support is just a text or call away.",
        "mental.crisis.btn": "Call 116 123",
        "mental.support_lang": "Support in your language",
        "mental.guides": "Guides & Resources",
        "women.subtitle": "Specific resources and care guides for women's health in Ireland.",
        "procedures.subtitle": "Essential guides for your immigration and administrative processes in Ireland.",
        "diff.easy": "Easy",
        "diff.medium": "Medium",
        "diff.hard": "Hard",
        "comm.mentors.title": "Mentors",
        "comm.mentors.subtitle": "Learn from those who have already walked the path. Connect and get practical advice.",
        "comm.mentors.become": "Become a Mentor",
        "comm.mentors.role": "Occupation",
        "comm.mentors.experience": "in Ireland",
        "comm.mentors.contact": "Contact",
        "comm.mentors.requestSent": "Request sent to",
        "pwa.install": "Get the App",
        "pwa.access": "Faster access",
        "pwa.btn": "Install",
        "pwa.iosInstructions": "To install: Tap the 'Share' icon and then 'Add to Home Screen'!",
        "comm.profile.interests": "Interests",
        "exercise.parks.subtitle": "Explore Dublin's green spaces. A directory of the best parks for walking, running, and relaxing.",
        "exercise.cycling.subtitle": "Cycling routes for all levels, from coastal paths to park loops.",
        "exercise.swimming.subtitle": "Safe spots for open water swimming in Dublin Bay.",
        "exercise.gyms.title": "Public Gyms & Pools",
        "exercise.gyms.subtitle": "Affordable, high-quality leisure centers run by Dublin City Council. No long contracts, great facilities.",
        "health.hero.subtitle": "Immediate access to vetted health resources for migrants.",
        "health.emergency.support": "General assistance",
        "health.emergency.hse": "General health info",
        "health.emergency.samaritans": "24/7 Mental support",
        "health.sections.women": "Maternity, screenings, and specialized care.",
        "health.sections.mental": "Support networks, psychologists, and well-being.",
        "health.sections.physio": "Recovery, community clinics, and specialists.",
        "health.gp.title": "Register with a local GP",
        "health.gp.desc": "Finding a doctor is the first step to accessing healthcare in Ireland. Use the official HSE finder.",
        "health.gp.btn": "Find GP Near Me",
        "health.enter": "Enter Section",
        "exercise.teams.title": "Register New Team",
        "exercise.teams.name": "Team Name",
        "exercise.teams.sport": "Sport (e.g. Football)",
        "exercise.teams.location": "Location",
        "exercise.teams.desc": "Short description / level / contact info",
        "exercise.teams.submit": "Submit for Authorization",
        "exercise.teams.success": "Team submitted for authorization! It will appear once approved.",
        "exercise.teams.community": "Community Teams",
        "exercise.teams.create": "Create Team",
        "lbl.maps.desc": "Open this location in Google Maps to start your navigation.",
        "lbl.maps.btn": "Open Maps",
        "comm.socialFit.subtitle": "Connect with others, share your steps, and grow together.",
        "comm.socialFit.milestone": "Community Milestone",
        "comm.socialFit.contribute": "Contribute KM",
        "comm.socialFit.addDistance": "Add your distance",
        "comm.socialFit.activityPlaceholder": "Activity (e.g. Hiking)",
        "comm.socialFit.progressTo": "Progress to 1000km",
        "comm.socialFit.completed": "COMPLETED!",
        "comm.socialFit.inProgress": "IN PROGRESS",
        "comm.socialFit.wall": "Community Wall",
        "comm.socialFit.createPost": "Create post",
        "comm.socialFit.newSession": "New Session",
        "comm.socialFit.submitApproval": "Submit for approval",
        "comm.socialFit.postSuccess": "Post submitted for authorization!",
        "comm.socialFit.contribSuccess": "Thank you! Your contribution will be added once authorized.",
        "comm.circles.title": "Circles",
        "comm.circles.subtitle": "Find your tribe. Groups based on shared interests and experiences.",
        "comm.circles.join": "Join",
        "comm.circles.exit": "Leave Group",
        "comm.events.title": "Upcoming Events",
        "comm.events.subtitle": "Free and community-focused meetups.",
        "comm.events.create": "Create Event",
        "comm.events.newTitle": "Create New Event",
        "comm.events.placeholder.title": "Event title (e.g. Picnic in St Stephens)",
        "comm.events.placeholder.date": "Date and Time",
        "comm.events.placeholder.location": "Location",
        "comm.events.placeholder.desc": "Description: What will we do? What to bring?",
        "comm.events.submit": "Submit for Authorization",
        "comm.events.success": "Event submitted! It will appear once authorized.",
        "comm.events.free": "FREE ENTRY",
        "comm.mentorModal.title": "Become a Mentor",
        "comm.mentorModal.subtitle": "Share your experience and help others in their journey.",
        "comm.mentorModal.fullName": "Full Name",
        "comm.mentorModal.email": "Email Address",
        "comm.mentorModal.origin": "Origin",
        "comm.mentorModal.years": "Years in IE",
        "comm.mentorModal.help": "How can you help?",
        "comm.mentorModal.submit": "Submit Application",
        "comm.mentorModal.success": "Your application has been submitted for authorization! It will appear once approved.",
        "comm.mentorModal.placeholder.name": "e.g. Maria Garcia",
        "comm.mentorModal.placeholder.email": "name@example.com",
        "comm.mentorModal.placeholder.origin": "Mexico, Brazil...",
        "comm.mentorModal.placeholder.years": "2 years, 6 months...",
        "comm.mentorModal.placeholder.occupation": "Nurse, Chef, Student...",
        "comm.mentorModal.placeholder.bio": "I can help with PPS appointments...",
        "forum.activeThreads": "active conversation threads",
        "forum.noThreads": "No threads yet. Start one!",
        "forum.replyPlaceholder": "Write a reply...",
        "forum.visitor": "Visitor",
        "legal.title": "Legal & Responsibility",
        "legal.disclaimer": "immiGrow is a purely informative platform. We do not provide legal or medical advice. The responsibility for any interaction, agreement, or meeting resulting from the use of this application rests exclusively with the user.",
        "legal.privacy": "Privacy",
        "legal.terms": "Terms",
        "legal.contact": "Contact",
        "more.badge.premium": "Premium Content",
        "more.title": "More Resources",
        "more.subtitle": "Dive deeper into life in Dublin with these specialized guides.",
        "more.install.title": "Take immiGrow everywhere",
        "more.install.desc": "Install the app on your home screen for faster access, offline mode, and a full-screen experience.",
        "more.install.button": "Install Now",
        "more.install.ios": "To install on iPhone: Tap 'Share' icon and then 'Add to Home Screen'.",
        "jobs.subtitle": "Your guide to finding work and building a career in Ireland.",
        "jobs.training": "Training & Education",
        "jobs.sb.desc": "Free or highly subsidized higher education courses.",
        "jobs.solas.desc": "Further Education and Training Authority in Ireland.",
        "tourism.subtitle": "Explore Dublin and surroundings. Trails, walks and landmarks.",
        "achievements.legacy": "Your Legacy",
        "achievements.hall": "Hall of Fame",
        "achievements.mastered": "You mastered {count} of {total} achievements!",
        "achievements.journey": "Journey Progress",
        "achievements.points": "points",
        "achievements.nextLevel": "Ready for Next Level?",
        "achievements.nextLevelDesc": "Complete more routes and help the community to unlock legendary achievements and exclusive rewards.",
        "vault.docPlaceholder": "e.g. Passport, IRP, GNIB",
        "vault.daysBefore": "days before",
        "vault.expired": "Expired",
        "vault.warning": "Warning",
        "vault.valid": "Valid",
        "vault.cancel": "Cancel",
        "comm.profile.story": "My Migrant Story",
        "comm.profile.languages": "Languages",
        "slang.title": "Speak like a Local",
        "slang.subtitle": "Common Dublin phrases and what they actually mean.",
        "slang.pro.title": "Pro Tip",
        "slang.pro.desc": "Irish English is very rhythmic. Don't worry about being perfect; just aim for the vibe. Using 'Grand' for everything is a great start!",
        "jobs.checklist.title": "Dublin Ready Checklist",
        "jobs.checklist.subtitle": "Essential steps for your job search.",
        "jobs.portals.title": "Top Job Portals",
        "jobs.tip.title": "Pro Tip: Cultural Fit",
        "jobs.tip.desc": "In Ireland, networking is often as important as your CV. Use LinkedIn to connect with employees at companies you're interested in and ask for an 'informal coffee chat'.",
        "achievements.explorer.title": "Dublin Explorer",
        "achievements.explorer.t1.title": "Getting Started",
        "achievements.explorer.t1.desc": "Complete 1 route",
        "achievements.explorer.t2.title": "Active Traveller",
        "achievements.explorer.t2.desc": "Complete 5 routes",
        "achievements.explorer.t3.title": "Master Explorer",
        "achievements.explorer.t3.desc": "Complete 10 routes",
        "achievements.nature.title": "Nature Lover",
        "achievements.nature.t1.title": "Fresh Air",
        "achievements.nature.t1.desc": "1 nature route",
        "achievements.nature.t2.title": "Trail Blazer",
        "achievements.nature.t2.desc": "3 nature routes",
        "achievements.nature.t3.title": "Mountain Guide",
        "achievements.nature.t3.desc": "5 nature routes",
        "achievements.social.title": "Community Star",
        "achievements.social.t1.title": "Team Player",
        "achievements.social.t1.desc": "First km contribution",
        "achievements.social.t2.title": "Supportive",
        "achievements.social.t2.desc": "Add 10km total",
        "achievements.social.t3.title": "Legendary",
        "achievements.social.t3.desc": "Add 50km total",
        "search.placeholder": "Search Dublin resources...",
        "event.welcome.title": "St. Patrick's Networking",
        "event.welcome.desc": "Celebrate St. Patrick's week with us! Connect with other migrants and share your journey.",
        "lbl.dublinIreland": "Dublin, Ireland",
    },
    es: {
        "nav.home": "Inicio",
        "nav.tourism": "Turismo Activo",
        "nav.parks": "Parques",
        "nav.swimming": "Natación",
        "nav.cycling": "Ciclismo",
        "nav.mental": "Salud Mental",
        "nav.women": "Salud de la Mujer",
        "nav.procedures": "Trámites",
        "nav.community": "Comunidad",
        "nav.vault": "Mi Bóveda",
        "nav.achievements": "Logros",
        "nav.socialFit": "Fitness Social",
        "nav.sportsTeams": "Equipos Deportivos",
        "nav.recipes": "Sabores de Casa",
        "nav.more": "Más",
        "nav.physical_activity": "Actividad",
        "nav.health": "Bienestar",
        "nav.admin": "Recursos",
        "nav.physiotherapy": "Fisioterapia",
        "nav.calculator": "Calculadora",
        "nav.jobs": "Trabajos",
        "nav.slang": "Habla como Local",
        "nav.active": "Rutas Activas",
        "nav.toolkit": "Caja de Herramientas",
        "toolkit.title": "Centro de Esenciales",
        "toolkit.subtitle": "Herramientas esenciales para tu vida en Dublín.",
        "tool.vault.desc": "Almacenamiento privado para tus trámites y fechas límite.",
        "tool.budgeter.desc": "Planifica tus finanzas con promedios locales reales.",
        "tool.career.desc": "Guías para encontrar trabajo y consejos para tu CV.",
        "tool.slang.desc": "Aprende el slang irlandés esencial para sonar como un local.",
        "tool.achievements.desc": "Sigue tu progreso y gana medallas mientras exploras.",
        "tool.community.desc": "Conecta con otros migrantes, únete a foros y busca eventos.",
        "tool.recipes.desc": "Recetario comunitario para cocinar tus platos latinos favoritos.",
        "tool.open": "Abrir",
        "nav.budgeter": "Presupuesto",
        "nav.career": "Centro de Carrera",
        "btn.visit": "Visitar Sitio Oficial",
        "lbl.backTo": "Volver a",
        "lbl.gettingThere": "Cómo llegar",
        "lbl.highlights": "Destacados",
        "lbl.offices": "Ubicación de Oficinas",
        "lbl.expiry": "Fecha de Vencimiento",
        "lbl.reminder": "Recordatorio de Renovación",
        "lbl.completeRoute": "Marcar como Completada",
        "lbl.completed": "¡Completada!",
        "lbl.badges": "Medallas",
        "lbl.trainWithMe": "Entrena Conmigo",
        "lbl.collectiveGoal": "Meta Colectiva",
        "hero.greeting": "Hola,",
        "hero.subtitle": "¿Listo para explorar?",
        "challenge.title": "Reto del Día",
        "challenge.name": "Paseo y Reflexión",
        "challenge.desc": "Encuentra un lugar tranquilo en St. Stephen's Green y dedica 10 minutos a observar tu entorno.",
        "btn.startNow": "Empezar Ahora",
        "common.viewAll": "Ver todos",
        "cat.body": "Cuerpo",
        "cat.explore": "Explorar",
        "cat.wellness": "Bienestar",
        "cat.social": "Social",
        "cat.admin": "Trámites",
        "cat.extras": "Extras",
        "home.quickAccess": "Acceso Rápido",
        "nav.lang": "Idioma",
        "nav.lang_name": "Español",
        "nav.lang_toggle": "English",
        "event.title": "Próximos Eventos",
        "event.subtitle": "Encuentros gratuitos y comunitarios.",
        "event.free": "Entrada Gratis",
        "event.viewFull": "Ver Calendario Completo",
        "forum.title": "Foro de la Comunidad",
        "forum.subtitle": "Haz preguntas, comparte consejos.",
        "forum.likes": "Me gusta",
        "forum.replies": "Respuestas",
        "forum.placeholder": "Pregunta algo...",
        "weather.good": "Perfecto para un paseo",
        "weather.bad": "Actividad en Interior Recomendada",
        "weather.clear": "Despejada",
        "weather.cloudy": "Parcialmente Nublado",
        "weather.rain": "Lloviendo",
        "weather.storm": "Tormenta",
        "weather.fog": "Niebla",
        "roadmap.title": "Hoja de Ruta",
        "roadmap.subtitle": "Pasos esenciales para tus primeras semanas",
        "search.placeholder": "Buscar recursos en Dublín...",
        "search.popular": "Palabras Clave",
        "search.results": "Resultados",
        "search.noResults": "No se encontraron resultados...",
        "exercise.title": "Fitness Universal",
        "exercise.subtitle": "Rutas y actividades adaptativas para todos. Elige una categoría para empezar a explorar.",
        "exercise.cat.parks.title": "Circuitos de Caminata en Parques",
        "exercise.cat.parks.desc": "Directorio de rutas de caminata en los mejores parques de Dublín (Phoenix, St. Anne's, Fairview, etc.).",
        "exercise.cat.swimming.title": "Natación en Aguas Abiertas",
        "exercise.cat.swimming.desc": "Directorio de lugares para nadar en el mar (Seapoint, Forty Foot, Vico, etc.).",
        "exercise.cat.cycling.title": "Rutas de Ciclismo",
        "exercise.cat.cycling.desc": "Ciclovías seguras y vías verdes (Clontarf, Phoenix Park, Canales).",
        "exercise.cat.gyms.title": "Gimnasios Públicos y Piscinas",
        "exercise.cat.gyms.desc": "Centros de ocio asequibles y de alta calidad gestionados por el Ayuntamiento de Dublín.",
        "exercise.cat.physio.title": "Fisioterapia y Recuperación",
        "exercise.cat.physio.desc": "Encuentra fisioterapeutas comunitarios y clínicas.",
        "exercise.cat.run.title": "Carrera Costera de Dublín",
        "exercise.cat.run.desc": "Ruta escénica de 5km por la costa. Disfruta la brisa marina y terreno plano.",
        "exercise.cat.walk.title": "Paseo del Río Liffey",
        "exercise.cat.walk.desc": "Un bucle suave de 2km a lo largo del Río Liffey. Perfecto para principiantes o rehabilitación.",
        "exercise.cat.teams.title": "Equipos Deportivos Comunitarios",
        "exercise.cat.teams.desc": "Únete a equipos amateur gratuitos de fútbol, rugby o GAA en parques como Fairview.",
        "comm.title": "Comunidad",
        "comm.subtitle": "El corazón de immiGrow. Conecta y crece junto a otros.",
        "comm.myStory": "Mi Historia",
        "comm.myStory.desc": "Personaliza tu perfil, cuenta tu historia y conecta con otros.",
        "comm.circles": "Círculos",
        "comm.circles.desc": "Grupos de apoyo para mujeres, latinos, nuevos migrantes y más.",
        "comm.mentors": "Mentores",
        "comm.mentors.desc": "Conecta con migrantes experimentados que pueden guiarte.",
        "comm.events": "Eventos",
        "comm.events.desc": "Encuentros presenciales, caminatas y cafés para socializar.",
        "comm.socialFit": "Social Fitness",
        "comm.socialFit.desc": "Entrena con otros, únete a retos y comparte tus logros.",
        "comm.identity": "Tu Identidad",
        "comm.namePlaceholder": "Tu nombre o apodo...",
        "vault.subtitle": "Tu centro personal de inmigración. Categorías, notas y recordatorios para tu vida en Irlanda.",
        "vault.quickNotes": "Notas de Copia Rápida",
        "vault.addNote": "+ Nueva Nota",
        "vault.saveNote": "Guardar Nota",
        "vault.myDocs": "Mis Documentos",
        "vault.newDoc": "+ Nuevo Doc",
        "vault.docName": "Nombre del Documento",
        "vault.category": "Categoría",
        "vault.reminderOn": "Aviso Activado",
        "vault.remove": "Borrar",
        "vault.createRecord": "Crear Registro",
        "vault.cat.identity": "Identidad",
        "vault.cat.housing": "Vivienda",
        "vault.cat.health": "Salud",
        "vault.cat.work": "Trabajo",
        "vault.content": "Contenido",
        "vault.label": "Etiqueta (ej: PPSN)",
        "safe.title": "Seguridad",
        "safe.disclaimer": "immiGrow es informativo. ¡Cuídate!",
        "safe.public": "Lugares Públicos",
        "safe.public.desc": "Queda siempre en lugares concurridos y bien iluminados, como cafés o parques principales.",
        "safe.inform": "Avisa a Terceros",
        "safe.inform.desc": "Informa a un amigo o familiar sobre a dónde vas y con quién te vas a encontrar.",
        "safe.privacy": "Cuida tu Privacidad",
        "safe.privacy.desc": "No compartas datos sensibles como tu cuenta bancaria o dirección exacta de inmediato.",
        "safe.instinct": "Confía en tu Instinto",
        "safe.instinct.desc": "Si algo no se siente bien, está bien irse o cancelar. Tu seguridad es lo primero.",
        "jobs.title": "Listo para Dublín",
        "mental.subtitle": "Recursos y apoyo para tu bienestar emocional.",
        "mental.professionals": "Directorio de Profesionales",
        "mental.crisis.title": "¿Necesitas ayuda ahora?",
        "mental.crisis.desc": "Apoyo confidencial 24/7 a un texto o llamada de distancia.",
        "mental.crisis.btn": "Llama 116 123",
        "mental.support_lang": "Apoyo en tu idioma",
        "mental.guides": "Guías y Recursos",
        "women.subtitle": "Recursos específicos y guías de atención para la salud de la mujer en Irlanda.",
        "procedures.subtitle": "Guías esenciales para tus procesos migratorios y administrativos en Irlanda.",
        "diff.easy": "Fácil",
        "diff.medium": "Medio",
        "diff.hard": "Difícil",
        "comm.mentors.title": "Mentores",
        "comm.mentors.subtitle": "Aprende de quienes ya recorrieron el camino. Conecta y recibe consejos prácticos.",
        "comm.mentors.become": "Quiero ser mentor",
        "comm.mentors.role": "Profesión",
        "comm.mentors.experience": "en Irlanda",
        "comm.mentors.contact": "Contactar",
        "comm.mentors.requestSent": "Solicitud enviada a",
        "pwa.install": "Descargar App",
        "pwa.access": "Acceso rápido",
        "pwa.btn": "Instalar",
        "pwa.iosInstructions": "Para instalar: ¡Toca el icono de 'Compartir' y luego 'Añadir a la pantalla de inicio'!",
        "comm.profile.interests": "Intereses",
        "exercise.parks.subtitle": "Explora los espacios verdes de Dublín. Un directorio de los mejores parques para caminar, correr y relajarse.",
        "exercise.cycling.subtitle": "Rutas de ciclismo para todos los niveles, desde caminos costeros hasta bucles en parques.",
        "exercise.swimming.subtitle": "Lugares seguros para nadar en aguas abiertas en la Bahía de Dublín.",
        "exercise.gyms.title": "Gimnasios Públicos y Piscinas",
        "exercise.gyms.subtitle": "Centros de ocio asequibles y de alta calidad gestionados por el Ayuntamiento de Dublín. Sin contratos largos, excelentes instalaciones.",
        "health.hero.subtitle": "Acceso inmediato a recursos de salud verificados para migrantes.",
        "health.emergency.support": "Apoyo general",
        "health.emergency.hse": "Info de salud general",
        "health.emergency.samaritans": "Apoyo mental 24/7",
        "health.sections.women": "Maternidad, chequeos y cuidado especializado.",
        "health.sections.mental": "Redes de apoyo, psicólogos y bienestar.",
        "health.sections.physio": "Recuperación, clínicas comunitarias y especialistas.",
        "health.gp.title": "Regístrate con un GP local",
        "health.gp.desc": "Encontrar un médico es el primer paso para acceder a la salud en Irlanda. Usa el buscador oficial de la HSE.",
        "health.gp.btn": "Buscar GP cercano",
        "health.enter": "Entrar",
        "exercise.teams.title": "Registrar Nuevo Equipo",
        "exercise.teams.name": "Nombre del Equipo",
        "exercise.teams.sport": "Deporte (ej: Fútbol)",
        "exercise.teams.location": "Ubicación",
        "exercise.teams.desc": "Descripción corta / nivel / contacto",
        "exercise.teams.submit": "Enviar para Autorización",
        "exercise.teams.success": "¡Equipo enviado para autorización! Aparecerá una vez sea aprobado.",
        "exercise.teams.community": "Equipos de la Comunidad",
        "exercise.teams.create": "Crear Equipo",
        "lbl.maps.desc": "Abre esta ubicación en Google Maps para comenzar tu navegación.",
        "lbl.maps.btn": "Abrir Mapas",
        "comm.socialFit.subtitle": "Conecta con otras, comparte tus pasos y creced juntas.",
        "comm.socialFit.milestone": "Meta Comunitaria",
        "comm.socialFit.contribute": "Aportar KM",
        "comm.socialFit.addDistance": "Suma tu distancia",
        "comm.socialFit.activityPlaceholder": "Actividad (ej: Caminata)",
        "comm.socialFit.progressTo": "Progreso hacia 1000km",
        "comm.socialFit.completed": "¡META LOGRADA!",
        "comm.socialFit.inProgress": "EN PROGRESO",
        "comm.socialFit.wall": "Muro de la Comunidad",
        "comm.socialFit.createPost": "Publicar anuncio",
        "comm.socialFit.newSession": "Nueva Sesión",
        "comm.socialFit.submitApproval": "Enviar para autorización",
        "comm.socialFit.postSuccess": "¡Anuncio enviado para autorización!",
        "comm.socialFit.contribSuccess": "¡Gracias! Tu contribución se añadirá una vez sea autorizada.",
        "comm.circles.title": "Círculos",
        "comm.circles.subtitle": "Encuentra tu tribu. Grupos basados en intereses y experiencias compartidas.",
        "comm.circles.join": "Unirme",
        "comm.circles.exit": "Salir del Grupo",
        "comm.events.title": "Próximos Eventos",
        "comm.events.subtitle": "Encuentros gratuitos y enfocados en la comunidad.",
        "comm.events.create": "Crear evento",
        "comm.events.newTitle": "Crear Nuevo Evento",
        "comm.events.placeholder.title": "Título del evento (ej: Picnic en St Stephens)",
        "comm.events.placeholder.date": "Fecha y Hora",
        "comm.events.placeholder.location": "Lugar",
        "comm.events.placeholder.desc": "Descripción: ¿Qué haremos? ¿Qué hay que llevar?",
        "comm.events.submit": "Enviar para Autorización",
        "comm.events.success": "¡Evento enviado! Aparecerá una vez sea autorizado.",
        "comm.events.free": "ENTRADA GRATIS",
        "comm.mentorModal.title": "Quiero ser mentor",
        "comm.mentorModal.subtitle": "Comparte tu experiencia y ayuda a otros en su camino.",
        "comm.mentorModal.fullName": "Nombre Completo",
        "comm.mentorModal.email": "Tu Correo",
        "comm.mentorModal.origin": "País",
        "comm.mentorModal.years": "Años en IE",
        "comm.mentorModal.help": "¿Cómo puedes ayudar?",
        "comm.mentorModal.submit": "Enviar Postulación",
        "comm.mentorModal.success": "¡Tu postulación ha sido enviada para autorización! Aparecerá una vez sea aprobada.",
        "comm.mentorModal.placeholder.name": "ej. Maria Garcia",
        "comm.mentorModal.placeholder.email": "nombre@ejemplo.com",
        "comm.mentorModal.placeholder.origin": "México, Brasil...",
        "comm.mentorModal.placeholder.years": "2 años, 6 meses...",
        "comm.mentorModal.placeholder.occupation": "Enfermera, Chef, Estudiante...",
        "comm.mentorModal.placeholder.bio": "Puedo ayudar con citas del PPS...",
        "forum.activeThreads": "hilos de conversación activos",
        "forum.noThreads": "No hay hilos aún. ¡Inicia uno!",
        "forum.replyPlaceholder": "Escribe una respuesta...",
        "forum.visitor": "Visitante",
        "legal.title": "Legal y Responsabilidad",
        "legal.disclaimer": "immiGrow es una plataforma puramente informativa. No proporcionamos asesoría legal ni médica. La responsabilidad de cualquier interacción, acuerdo o encuentro resultante del uso de esta aplicación recae exclusivamente en el usuario.",
        "legal.privacy": "Privacidad",
        "legal.terms": "Términos",
        "legal.contact": "Contacto",
        "more.badge.premium": "Contenido Premium",
        "more.title": "Más Recursos",
        "more.subtitle": "Explora más sobre la vida en Dublín con estas guías especializadas.",
        "more.install.title": "Lleva immiGrow a todas partes",
        "more.install.desc": "Instala la app en tu pantalla de inicio para un acceso más rápido, modo sin conexión y experiencia completa.",
        "more.install.button": "Instalar Ahora",
        "more.install.ios": "Para instalar en iPhone: Toca el icono de 'Compartir' y luego 'Añadir a la pantalla de inicio'.",
        "jobs.subtitle": "Tu guía para encontrar trabajo y construir una carrera en Irlanda.",
        "jobs.training": "Capacitación y Educación",
        "jobs.sb.desc": "Cursos de educación superior gratuitos o altamente subsidiados.",
        "jobs.solas.desc": "Autoridad de Educación y Formación Profesional en Irlanda.",
        "tourism.subtitle": "Explora Dublín y sus alrededores. Senderos, caminatas y lugares emblemáticos.",
        "achievements.legacy": "Tu Legado",
        "achievements.hall": "Salón de la Fama",
        "achievements.mastered": "¡Has dominado {count} de {total} logros!",
        "achievements.journey": "Progreso del Viaje",
        "achievements.points": "puntos",
        "achievements.nextLevel": "¿Listo para el Siguiente Nivel?",
        "achievements.nextLevelDesc": "Completa más rutas y ayuda a la comunidad para desbloquear logros legendarios y recompensas exclusivas.",
        "vault.docPlaceholder": "ej. Pasaporte, IRP, GNIB",
        "vault.daysBefore": "días antes",
        "vault.expired": "Expirado",
        "vault.warning": "Advertencia",
        "vault.valid": "Válido",
        "vault.cancel": "Cancelar",
        "comm.profile.story": "Mi Historia Migrante",
        "comm.profile.languages": "Idiomas",
        "slang.title": "Habla como un local",
        "slang.subtitle": "Frases comunes de Dublín y lo que realmente significan.",
        "slang.pro.title": "Consejo Pro",
        "slang.pro.desc": "El inglés de Irlanda es muy rítmico. No te preocupes por ser perfecta; intenta captar la vibra. ¡Usar 'Grand' para todo es un excelente comienzo!",
        "jobs.checklist.title": "Preparación para el Empleo",
        "jobs.checklist.subtitle": "Pasos esenciales para tu búsqueda de empleo.",
        "jobs.portals.title": "Portales de Empleo Principales",
        "jobs.tip.title": "Consejo: Fit Cultural",
        "jobs.tip.desc": "En Irlanda, el networking es tan importante como tu CV. Usa LinkedIn para conectar con empleados de empresas que te interesen y pide un 'café informal' (informal coffee chat).",
        "achievements.explorer.title": "Exploradora de Dublín",
        "achievements.explorer.t1.title": "Empezando",
        "achievements.explorer.t1.desc": "Completa 1 ruta",
        "achievements.explorer.t2.title": "Viajera Activa",
        "achievements.explorer.t2.desc": "Completa 5 rutas",
        "achievements.explorer.t3.title": "Maestra Exploradora",
        "achievements.explorer.t3.desc": "Completa 10 rutas",
        "achievements.nature.title": "Amante de la Naturaleza",
        "achievements.nature.t1.title": "Aire Fresco",
        "achievements.nature.t1.desc": "1 ruta de naturaleza",
        "achievements.nature.t2.title": "Pionera de Senderos",
        "achievements.nature.t2.desc": "3 rutas de naturaleza",
        "achievements.nature.t3.title": "Guía de Montaña",
        "achievements.nature.t3.desc": "5 rutas de naturaleza",
        "achievements.social.title": "Estrella de la Comunidad",
        "achievements.social.t1.title": "Jugadora de Equipo",
        "achievements.social.t1.desc": "Primera contribución de km",
        "achievements.social.t2.title": "Solidaria",
        "achievements.social.t2.desc": "Suma 10km en total",
        "achievements.social.t3.title": "Legendaria",
        "achievements.social.t3.desc": "Suma 50km en total",
        "search.placeholder": "Buscar recursos en Dublín...",
        "event.welcome.title": "Networking de San Patricio",
        "event.welcome.desc": "¡Celebra la semana de San Patricio con nosotros! Conecta con otras personas migrantes y comparte tu experiencia.",
        "lbl.dublinIreland": "Dublín, Irlanda",
    },
    pt: {
        "nav.home": "Início",
        "nav.tourism": "Turismo Ativo",
        "nav.parks": "Parques",
        "nav.swimming": "Natação",
        "nav.cycling": "Ciclismo",
        "nav.mental": "Saúde Mental",
        "nav.women": "Saúde da Mulher",
        "nav.procedures": "Processos",
        "nav.community": "Comunidade",
        "nav.vault": "Meu Cofre",
        "nav.achievements": "Conquistas",
        "nav.socialFit": "Fitness Social",
        "nav.sportsTeams": "Equipes Esportivas",
        "nav.recipes": "Sabores de Casa",
        "nav.more": "Mais",
        "nav.physical_activity": "Atividade",
        "nav.health": "Saúde",
        "nav.admin": "Recursos",
        "nav.physiotherapy": "Fisio",
        "nav.calculator": "Calculadora",
        "nav.jobs": "Pronto para Dublin",
        "nav.slang": "Fale como um Local",
        "nav.active": "Rotas Ativas",
        "nav.toolkit": "Caixa de Ferramentas",
        "toolkit.title": "Central de Essenciais",
        "toolkit.subtitle": "Ferramentas essenciais para sua vida em Dublin.",
        "tool.vault.desc": "Armazenamento privado para seus prazos e documentos.",
        "tool.budgeter.desc": "Planeje suas finanças com médias locais de Dublin.",
        "tool.career.desc": "Guias para encontrar trabalho e dicas de currículo.",
        "tool.slang.desc": "Aprenda gírias essenciais para soar como um local.",
        "tool.achievements.desc": "Acompanhe seu progresso e ganhe medalhas.",
        "tool.community.desc": "Conecte-se com outros migrantes, participe de fóruns e eventos.",
        "tool.recipes.desc": "Livro de receitas comunitário para cozinhar seus pratos favoritos.",
        "tool.open": "Abrir",
        "nav.budgeter": "Orçamento",
        "nav.career": "Centro de Carreira",
        "btn.visit": "Visitar Site Oficial",
        "lbl.backTo": "Voltar para",
        "lbl.gettingThere": "Como chegar",
        "lbl.highlights": "Destaques",
        "lbl.offices": "Localização",
        "lbl.expiry": "Data de Expiração",
        "lbl.reminder": "Lembrete de Renovação",
        "lbl.completeRoute": "Marcar como Concluída",
        "lbl.completed": "Concluído!",
        "lbl.badges": "Medalhas",
        "lbl.trainWithMe": "Treine Comigo",
        "lbl.collectiveGoal": "Meta Colectiva",
        "hero.greeting": "Olá,",
        "hero.subtitle": "Pronto para explorar?",
        "challenge.title": "Desafio do Dia",
        "challenge.name": "Passeio e Reflexão",
        "challenge.desc": "Encontre um lugar calmo no St. Stephen's Green e tire 10 minutos para observar seu redor.",
        "btn.startNow": "Começar Agora",
        "common.viewAll": "Ver todos",
        "cat.body": "Corpo",
        "cat.explore": "Explorar",
        "cat.wellness": "Bem-estar",
        "cat.social": "Social",
        "cat.admin": "Processos",
        "cat.extras": "Extras",
        "home.quickAccess": "Acesso Rápido",
        "nav.lang": "Idioma",
        "nav.lang_name": "Português",
        "nav.lang_toggle": "Español",
        "event.title": "Próximos Eventos",
        "event.subtitle": "Encontros gratuitos e comunitários.",
        "event.free": "Entrada Grátis",
        "event.viewFull": "Ver Calendário Completo",
        "forum.title": "Fórum da Comunidade",
        "forum.subtitle": "Tire dúvidas, compartilhe dicas.",
        "forum.likes": "Curtidas",
        "forum.replies": "Respostas",
        "forum.placeholder": "Pergunte algo...",
        "weather.good": "Perfeito para um passeio",
        "weather.bad": "Atividade Interna Recomendada",
        "weather.clear": "Céu Limpo",
        "weather.cloudy": "Parcialmente Nublado",
        "weather.rain": "Chovendo",
        "weather.storm": "Tempestade",
        "weather.fog": "Neblina",
        "roadmap.title": "Guia do Recém-Chegado",
        "roadmap.subtitle": "Passos essenciais para suas primeiras semanas",
        "search.placeholder": "Buscar recursos em Dublin...",
        "search.popular": "Palavras-chave",
        "search.results": "Resultados",
        "search.noResults": "Nenhum resultado encontrado...",
        "exercise.title": "Fitness Universal",
        "exercise.subtitle": "Rotas e atividades adaptáveis para todos. Escolha uma categoria para começar.",
        "exercise.cat.parks.title": "Circuitos em Parques",
        "exercise.cat.parks.desc": "Diretório de rotas nos melhores parques de Dublin (Phoenix, St. Anne's, Fairview, etc.).",
        "exercise.cat.swimming.title": "Natação em Mar Aberto",
        "exercise.cat.swimming.desc": "Diretório de pontos de natação no mar (Seapoint, Forty Foot, Vico, etc.).",
        "exercise.cat.cycling.title": "Rotas de Ciclismo",
        "exercise.cat.cycling.desc": "Ciclovias seguras e vias verdes (Clontarf, Phoenix Park, Canais).",
        "exercise.cat.gyms.title": "Ginasios Públicos e Piscinas",
        "exercise.cat.gyms.desc": "Centros de lazer acessíveis e de alta qualidade geridos pela Prefeitura.",
        "exercise.cat.physio.title": "Fisioterapia e Recuperação",
        "exercise.cat.physio.desc": "Encontre fisioterapeutas comunitários e clínicas.",
        "exercise.cat.run.title": "Corrida Costeira de Dublin",
        "exercise.cat.run.desc": "Rota cênica de 5km pela costa. Aproveite a brisa do mar e terreno plano.",
        "exercise.cat.walk.title": "Passeio pelo Rio Liffey",
        "exercise.cat.walk.desc": "Um circuito suave de 2km ao longo do Rio Liffey. Perfeito para iniciantes.",
        "exercise.cat.teams.title": "Times Esportivos Comunitários",
        "exercise.cat.teams.desc": "Participe de times amadores gratuitos de Futebol, Rugby ou GAA em parques locais.",
        "comm.title": "Comunidade",
        "comm.subtitle": "O coração do immiGrow. Conecte-se e cresça com os outros.",
        "comm.myStory": "Minha História",
        "comm.myStory.desc": "Personalize seu perfil, conte sua história e conecte-se com outros.",
        "comm.circles": "Círculos",
        "comm.circles.desc": "Grupos de apoio para mulheres, latinos, recém-chegados e mais.",
        "comm.mentors": "Mentores",
        "comm.mentors.desc": "Conecte-se com migrantes experientes que podem guiá-lo.",
        "comm.events": "Eventos",
        "comm.events.desc": "Encontros presenciais, caminhadas e café para socializar.",
        "comm.socialFit": "Fitness Social",
        "comm.socialFit.desc": "Treine com outros, participe de desafios e compartilhe conquistas.",
        "comm.identity": "Sua Identidade",
        "comm.namePlaceholder": "Seu nome ou apelido...",
        "vault.subtitle": "Seu centro pessoal de imigração. Categorias, notas e lembretes para sua vida na Irlanda.",
        "vault.quickNotes": "Notas de Cópia Rápida",
        "vault.addNote": "+ Nova Nota",
        "vault.saveNote": "Salvar Nota",
        "vault.myDocs": "Meus Documentos",
        "vault.newDoc": "+ Novo Doc",
        "vault.docName": "Nome do Documento",
        "vault.category": "Categoria",
        "vault.reminderOn": "Lembrete Ativado",
        "vault.remove": "Remover",
        "vault.createRecord": "Criar Registro",
        "vault.cat.identity": "Identidade",
        "vault.cat.housing": "Habitação",
        "vault.cat.health": "Saúde",
        "vault.cat.work": "Trabalho",
        "vault.content": "Conteúdo",
        "vault.label": "Etiqueta (ex: PPSN)",
        "safe.title": "Segurança",
        "safe.disclaimer": "immiGrow é informativo. Cuide-se!",
        "safe.public": "Locais Públicos",
        "safe.public.desc": "Sempre se encontre em áreas públicas movimentadas e bem iluminadas, como cafés ou parques principais.",
        "safe.inform": "Informe Alguém",
        "safe.inform.desc": "Avise um amigo ou familiar sobre para onde você está indo e com quem vai se encontrar.",
        "safe.privacy": "Proteja sua Privacidade",
        "safe.privacy.desc": "Não compartilhe detalhes confidenciais, como sua conta bancária ou endereço residencial, imediatamente.",
        "safe.instinct": "Confie no seu Instinto",
        "safe.instinct.desc": "Se algo parecer errado, tudo bem ir embora ou cancelar. Sua segurança vem em primeiro lugar.",
        "jobs.title": "Pronto para Dublin",
        "mental.subtitle": "Recursos e apoio para o seu bem-estar emocional.",
        "mental.professionals": "Diretório de Profissionais",
        "mental.crisis.title": "Precisa de ajuda agora?",
        "mental.crisis.desc": "Apoio confidencial 24/7 a apenas uma mensagem ou ligação.",
        "mental.crisis.btn": "Ligue 116 123",
        "mental.support_lang": "Apoio no seu idioma",
        "mental.guides": "Guias e Recursos",
        "women.subtitle": "Recursos específicos e guias de cuidados para a saúde da mulher na Irlanda.",
        "procedures.subtitle": "Guias essenciais para seus processos imigratórios e administrativos na Irlanda.",
        "jobs.subtitle": "Seu guia para encontrar trabalho e construir carreira na Irlanda.",
        "jobs.training": "Treinamento e Educação",
        "jobs.sb.desc": "Cursos de ensino superior gratuitos ou altamente subsidiados.",
        "jobs.solas.desc": "Autoridade de Educação e Treinamento Profissional na Irlanda.",
        "tourism.subtitle": "Explore Dublin e arredores. Trilhas, caminhadas e pontos turísticos.",
        "diff.easy": "Fácil",
        "diff.medium": "Médio",
        "diff.hard": "Difícil",
        "comm.mentors.title": "Mentores",
        "comm.mentors.subtitle": "Aprenda com quem já percorreu o caminho. Conecte-se e receba conselhos práticos.",
        "comm.mentors.become": "Quero ser mentor",
        "comm.mentors.role": "Profissão",
        "comm.mentors.experience": "na Irlanda",
        "comm.mentors.contact": "Contatar",
        "comm.mentors.requestSent": "Solicitação enviada para",
        "pwa.install": "Obter App",
        "pwa.access": "Acesso rápido",
        "pwa.btn": "Instalar",
        "pwa.iosInstructions": "Para instalar: Toque no ícone de 'Compartilhar' e depois em 'Adicionar à Tela de Início'!",
        "achievements.legacy": "Seu Legado",
        "achievements.hall": "Galeria da Fama",
        "achievements.mastered": "Você dominou {count} de {total} conquistas!",
        "achievements.journey": "Progresso da Jornada",
        "achievements.points": "pontos",
        "achievements.nextLevel": "Pronto para o Próximo Nível?",
        "achievements.nextLevelDesc": "Complete mais rotas e ajude a comunidade para desbloquear conquistas lendárias e recompensas exclusivas.",
        "vault.docPlaceholder": "ex: Passaporte, IRP, GNIB",
        "vault.daysBefore": "dias antes",
        "vault.expired": "Expirado",
        "vault.warning": "Aviso",
        "vault.valid": "Válido",
        "vault.cancel": "Cancelar",
        "comm.profile.story": "Minha História Migrante",
        "comm.profile.languages": "Idiomas",
        "comm.profile.interests": "Interesses",
        "comm.socialFit.subtitle": "Conecte-se com outras pessoas, compartilhe seus passos e cresçam juntas.",
        "comm.socialFit.milestone": "Meta Comunitária",
        "comm.socialFit.contribute": "Aportar KM",
        "comm.socialFit.addDistance": "Soma sua distância",
        "comm.socialFit.activityPlaceholder": "Atividade (ex: Caminhada)",
        "comm.socialFit.progressTo": "Progresso para 1000km",
        "comm.socialFit.completed": "CONCLUÍDO!",
        "comm.socialFit.inProgress": "EM PROGRESSO",
        "comm.socialFit.wall": "Mural da Comunidade",
        "comm.socialFit.createPost": "Criar postagem",
        "comm.socialFit.newSession": "Nova Sessão",
        "comm.socialFit.submitApproval": "Enviar para autorização",
        "comm.socialFit.postSuccess": "Postagem enviada para autorização!",
        "comm.socialFit.contribSuccess": "Obrigado! Sua contribuição será adicionada assim que for autorizada.",
        "comm.circles.title": "Círculos",
        "comm.circles.subtitle": "Encontre sua tribo. Grupos baseados em interesses e experiências compartilhadas.",
        "comm.circles.join": "Participar",
        "comm.circles.exit": "Sair do Grupo",
        "comm.events.title": "Próximos Eventos",
        "comm.events.subtitle": "Encontros gratuitos e focados na comunidade.",
        "comm.events.create": "Criar Evento",
        "comm.events.newTitle": "Criar Novo Evento",
        "comm.events.placeholder.title": "Título do evento (ex: Picnic no St Stephens)",
        "comm.events.placeholder.date": "Data e Hora",
        "comm.events.placeholder.location": "Local",
        "comm.events.placeholder.desc": "Descrição: O que faremos? O que levar?",
        "comm.events.submit": "Enviar para Autorização",
        "comm.events.success": "Evento enviado! Aparecerá assim que for autorizado.",
        "comm.events.free": "ENTRADA GRATUITA",
        "comm.mentorModal.title": "Vire um Mentor",
        "comm.mentorModal.subtitle": "Compartilhe sua experiência e ajude outros em sua jornada.",
        "comm.mentorModal.fullName": "Nome Completo",
        "comm.mentorModal.email": "Seu E-mail",
        "comm.mentorModal.origin": "País de Origem",
        "comm.mentorModal.years": "Anos na Irlanda",
        "comm.mentorModal.help": "Como você pode ajudar?",
        "comm.mentorModal.submit": "Enviar Candidatura",
        "comm.mentorModal.success": "Sua candidatura foi enviada para autorização! Aparecerá assim que for aprovada.",
        "comm.mentorModal.placeholder.name": "ex. Maria Garcia",
        "comm.mentorModal.placeholder.email": "nome@exemplo.com",
        "comm.mentorModal.placeholder.origin": "Brasil, Portugal...",
        "comm.mentorModal.placeholder.years": "2 anos, 6 meses...",
        "comm.mentorModal.placeholder.occupation": "Enfermeira, Chef, Estudante...",
        "comm.mentorModal.placeholder.bio": "Posso ajudar com agendamentos do PPS...",
        "forum.activeThreads": "tópicos de conversa ativos",
        "forum.noThreads": "Ainda não há tópicos. Comece um!",
        "forum.replyPlaceholder": "Escreva uma resposta...",
        "forum.visitor": "Visitante",
        "slang.title": "Fale como um Local",
        "slang.subtitle": "Frases comuns de Dublin e o que elas realmente significam.",
        "slang.pro.title": "Dica Pro",
        "slang.pro.desc": "O inglês irlandês é muito rítmico. Não se preocupe em ser perfeito; apenas procure sentir a 'vibe'. Usar 'Grand' para tudo é um ótimo começo!",
        "jobs.checklist.title": "Lista de Preparação para Dublin",
        "jobs.checklist.subtitle": "Passos essenciais para sua busca por emprego.",
        "jobs.portals.title": "Principais Portais de Emprego",
        "jobs.tip.title": "Dica Pro: Fit Cultural",
        "jobs.tip.desc": "Na Irlanda, o networking costuma ser tão importante quanto o seu currículo. Use o LinkedIn para se conectar com funcionários de empresas do seu interesse e peça uma 'conversa informal para um café'.",
        "achievements.explorer.title": "Exploradora de Dublin",
        "achievements.explorer.t1.title": "Começando",
        "achievements.explorer.t1.desc": "Complete 1 rota",
        "achievements.explorer.t2.title": "Viajante Ativa",
        "achievements.explorer.t2.desc": "Complete 5 rotas",
        "achievements.explorer.t3.title": "Mestre Exploradora",
        "achievements.explorer.t3.desc": "Complete 10 rotas",
        "achievements.nature.title": "Amante da Natureza",
        "achievements.nature.t1.title": "Ar Puro",
        "achievements.nature.t1.desc": "1 rota de natureza",
        "achievements.nature.t2.title": "Pioneira de Trilhas",
        "achievements.nature.t2.desc": "3 rotas de natureza",
        "achievements.nature.t3.title": "Guia de Montanha",
        "achievements.nature.t3.desc": "5 rotas de natureza",
        "achievements.social.title": "Estrela da Comunidade",
        "achievements.social.t1.title": "Jogadora de Equipe",
        "achievements.social.t1.desc": "Primeira contribuição de km",
        "achievements.social.t2.title": "Solidária",
        "achievements.social.t2.desc": "Some 10km no total",
        "achievements.social.t3.title": "Lendária",
        "achievements.social.t3.desc": "Some 50km no total",
        "search.placeholder": "Pesquisar recursos em Dublin...",
        "event.welcome.title": "Networking de São Patrício",
        "event.welcome.desc": "Celebre a semana de São Patrício conosco! Conecte-se com outros imigrantes e compartilhe sua jornada.",
        "lbl.dublinIreland": "Dublin, Irlanda",
    }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [language, setLanguage] = useState<Language>("en");
    const [userName, setUserNameState] = useState<string>("");

    useEffect(() => {
        const savedLang = localStorage.getItem('iGrow_lang') as Language;
        if (savedLang) setLanguage(savedLang);

        const savedName = localStorage.getItem('iGrow_user');
        if (savedName) setUserNameState(savedName || "");
    }, []);

    const setUserName = (name: string) => {
        setUserNameState(name);
        localStorage.setItem('iGrow_user', name);
    };

    const changeLanguage = (newLang: Language) => {
        setLanguage(newLang);
        localStorage.setItem('iGrow_lang', newLang);
    };

    const toggleLanguage = () => {
        setLanguage((prev) => {
            let newLang: Language;
            if (prev === "en") newLang = "pt";
            else if (prev === "pt") newLang = "es";
            else newLang = "en";

            localStorage.setItem('iGrow_lang', newLang);
            return newLang;
        });
    };

    const t = (key: string) => {
        const dict = dictionaries[language] as Record<string, string>;
        return dict[key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage: changeLanguage, toggleLanguage, t, userName, setUserName }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error("useLanguage must be used within a LanguageProvider");
    }
    return context;
}
