"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "es" | "pt";

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    toggleLanguage: () => void;
    t: (key: string) => string;
    userName: string;
    setUserName: (name: string) => void;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const dictionaries = {
    en: {
        "nav.home": "Home",
        "nav.tourism": "Active Tourism",
        "nav.parks": "Parks",
        "nav.swimming": "Swimming",
        "nav.cycling": "Cycling",
        "nav.mental": "Mental Health",
        "nav.women": "Women's Health",
        "nav.procedures": "Procedures",
        "nav.community": "Community",
        "nav.vault": "My Vault",
        "nav.achievements": "Achievements",
        "nav.socialFit": "Social Fitness",
        "nav.sportsTeams": "Sports Teams",
        "nav.recipes": "Taste of Home",
        "nav.more": "More",
        "nav.physical_activity": "Physical",
        "nav.health": "Health",
        "nav.admin": "Resources",
        "nav.physiotherapy": "Physio",
        "nav.calculator": "Calculator",
        "nav.jobs": "Jobs & Careers",
        "nav.slang": "Speak like a Local",
        "nav.active": "Active Tourism",
        "nav.toolkit": "Toolkit",
        "toolkit.title": "Essentials Hub",
        "toolkit.subtitle": "Essential tools for your life in Dublin.",
        "tool.vault.desc": "Private storage for your immigration deadlines and documents.",
        "tool.budgeter.desc": "Plan your finances with real local averages for Dublin.",
        "tool.career.desc": "Guides for finding work, CV tips, and recruitment in Ireland.",
        "tool.slang.desc": "Learn essential Irish slang to sound like a native.",
        "tool.achievements.desc": "Track your progress and earn badges as you explore.",
        "tool.community.desc": "Connect with other migrants, join forums, and find events.",
        "tool.recipes.desc": "Community recipe book to cook your favorite Latin dishes.",
        "tool.open": "Open Tool",
        "nav.budgeter": "Budgeter",
        "nav.career": "Career Hub",
        "btn.visit": "Visit Official Website",
        "lbl.backTo": "Back to",
        "lbl.gettingThere": "Getting There",
        "lbl.highlights": "Highlights",
        "lbl.offices": "Office Locations",
        "lbl.expiry": "Expiry Date",
        "lbl.reminder": "Renewal Reminder",
        "lbl.completeRoute": "Mark as Completed",
        "lbl.completed": "Completed!",
        "lbl.badges": "Badges",
        "lbl.trainWithMe": "Train With Me",
        "lbl.collectiveGoal": "Collective Goal",
        "hero.greeting": "G'day,",
        "hero.subtitle": "Ready to explore?",
        "challenge.title": "Daily Challenge",
        "challenge.name": "Nature Walk & Reflection",
        "challenge.desc": "Find a quiet spot in St. Stephen's Green and spend 10 minutes observing the locals.",
        "btn.startNow": "Start Now",
        "common.viewAll": "View all",
        "cat.body": "Body",
        "cat.explore": "Explore",
        "cat.wellness": "Wellness",
        "cat.social": "Social",
        "cat.admin": "Admin",
        "cat.extras": "Extras",
        "home.quickAccess": "Quick Access",
        "nav.lang": "Language",
        "nav.lang_name": "English",
        "nav.lang_toggle": "Português",
        "event.title": "Upcoming Events",
        "event.subtitle": "Free and community-focused meetups.",
        "event.free": "Free Entry",
        "event.viewFull": "View Full Calendar",
        "forum.title": "Community Forum",
        "forum.subtitle": "Ask questions, share tips.",
        "forum.likes": "Likes",
        "forum.replies": "Replies",
        "forum.placeholder": "Ask something...",
        "weather.good": "Perfect for a walk",
        "weather.bad": "Indoor Activity Recommended",
        "weather.clear": "Clear",
        "weather.cloudy": "Partly Cloudy",
        "weather.rain": "Raining",
        "weather.storm": "Thunderstorm",
        "weather.fog": "Foggy",
        "roadmap.title": "Newcomer Roadmap",
        "roadmap.subtitle": "Essential steps for your first weeks",
        "search.placeholder": "Search Dublin resources...",
        "search.popular": "Popular Keywords",
        "search.results": "Results",
        "search.noResults": "No results found...",
        "exercise.title": "Universal Fitness",
        "exercise.subtitle": "Adaptive routes and activities for everyone. Choose a category to start exploring.",
        "exercise.cat.parks.title": "Park Walking Circuits",
        "exercise.cat.parks.desc": "Directory of walking routes in Dublin's best parks (Phoenix, St. Anne's, Fairview, etc.).",
        "exercise.cat.swimming.title": "Open Water Swimming",
        "exercise.cat.swimming.desc": "Directory of sea swimming spots (Seapoint, Forty Foot, Vico, etc.).",
        "exercise.cat.cycling.title": "Cycling Routes",
        "exercise.cat.cycling.desc": "Safe cycle lanes and greenways (Clontarf, Phoenix Park, Canals).",
        "exercise.cat.gyms.title": "Public Gyms & Pools",
        "exercise.cat.gyms.desc": "Affordable, high-quality leisure centers run by Dublin City Council.",
        "exercise.cat.physio.title": "Physiotherapy & Recovery",
        "exercise.cat.physio.desc": "Find community physiotherapists and clinics.",
        "exercise.cat.run.title": "Dublin Bay Coastal Run",
        "exercise.cat.run.desc": "5km scenic route along the coast. Enjoy the sea breeze and flat terrain.",
        "exercise.cat.walk.title": "Liffey River Walk",
        "exercise.cat.walk.desc": "A gentle 2km loop along the River Liffey. Perfect for beginners or rehabilitation.",
        "exercise.cat.teams.title": "Community Sports Teams",
        "exercise.cat.teams.desc": "Join free amateur teams for Football, Rugby, or GAA (Gaelic games) in parks like Fairview Park.",
        "comm.title": "Community",
        "comm.subtitle": "The heart of immiGrow. Connect and grow with others.",
        "comm.myStory": "My Story",
        "comm.myStory.desc": "Personalize your profile, tell your story and connect with others.",
        "comm.circles": "Circles",
        "comm.circles.desc": "Support groups for women, Latinos, newcomers, and more.",
        "comm.mentors": "Mentors",
        "comm.mentors.desc": "Connect with experienced migrants who can guide you.",
        "comm.events": "Events",
        "comm.events.desc": "Face-to-face meetings, walks, and coffee to socialize.",
        "comm.socialFit": "Social Fitness",
        "comm.socialFit.desc": "Train with others, join challenges and share achievements.",
        "comm.identity": "Your Identity",
        "comm.namePlaceholder": "Your name or nickname...",
        "vault.subtitle": "Your personal immigration hub. Categories, notes, and reminders for your life in Ireland.",
        "vault.quickNotes": "Quick Copy Notes",
        "vault.addNote": "+ Add Note",
        "vault.saveNote": "Save Note",
        "vault.myDocs": "My Documents",
        "vault.newDoc": "+ New Doc",
        "vault.docName": "Document Name",
        "vault.category": "Category",
        "vault.reminderOn": "Reminder ON",
        "vault.remove": "Remove",
        "vault.createRecord": "Create Record",
        "vault.cat.identity": "Identity",
        "vault.cat.housing": "Housing",
        "vault.cat.health": "Health",
        "vault.cat.work": "Work",
        "vault.content": "Content",
        "vault.label": "Label (e.g. PPSN)",
        "safe.title": "Safety First",
        "safe.disclaimer": "immiGrow is informative. Stay safe!",
        "safe.public": "Public Places",
        "safe.public.desc": "Always meet in busy, well-lit public areas like cafes or main parks.",
        "safe.inform": "Inform Someone",
        "safe.inform.desc": "Let a friend or family member know where you are going and who you are meeting.",
        "safe.privacy": "Protect Privacy",
        "safe.privacy.desc": "Don't share sensitive details like your bank account or home address immediately.",
        "safe.instinct": "Trust Your Instinct",
        "safe.instinct.desc": "If something feels wrong, it's okay to leave or cancel. Your safety comes first.",
        "jobs.title": "Dublin Ready",
        "mental.subtitle": "Resources and support for your emotional well-being.",
        "mental.professionals": "Directory of Professionals",
        "mental.crisis.title": "Need help right now?",
        "mental.crisis.desc": "Confidential 24/7 support is just a text or call away.",
        "mental.crisis.btn": "Call 116 123",
        "mental.support_lang": "Support in your language",
        "mental.guides": "Guides & Resources",
        "women.subtitle": "Specific resources and care guides for women's health in Ireland.",
        "procedures.subtitle": "Essential guides for your immigration and administrative processes in Ireland.",
        "diff.easy": "Easy",
        "diff.medium": "Medium",
        "diff.hard": "Hard",
    },
    es: {
        "nav.home": "Inicio",
        "nav.tourism": "Turismo Activo",
        "nav.parks": "Parques",
        "nav.swimming": "Natación",
        "nav.cycling": "Ciclismo",
        "nav.mental": "Salud Mental",
        "nav.women": "Salud de la Mujer",
        "nav.procedures": "Trámites",
        "nav.community": "Comunidad",
        "nav.vault": "Mi Bóveda",
        "nav.achievements": "Logros",
        "nav.socialFit": "Fitness Social",
        "nav.sportsTeams": "Equipos Deportivos",
        "nav.recipes": "Sabores de Casa",
        "nav.more": "Más",
        "nav.physical_activity": "Actividad",
        "nav.health": "Bienestar",
        "nav.admin": "Recursos",
        "nav.physiotherapy": "Fisioterapia",
        "nav.calculator": "Calculadora",
        "nav.jobs": "Trabajos",
        "nav.slang": "Habla como Local",
        "nav.active": "Rutas Activas",
        "nav.toolkit": "Caja de Herramientas",
        "toolkit.title": "Centro de Esenciales",
        "toolkit.subtitle": "Herramientas esenciales para tu vida en Dublín.",
        "tool.vault.desc": "Almacenamiento privado para tus trámites y fechas límite.",
        "tool.budgeter.desc": "Planifica tus finanzas con promedios locales reales.",
        "tool.career.desc": "Guías para encontrar trabajo y consejos para tu CV.",
        "tool.slang.desc": "Aprende el slang irlandés esencial para sonar como un local.",
        "tool.achievements.desc": "Sigue tu progreso y gana medallas mientras exploras.",
        "tool.community.desc": "Conecta con otros migrantes, únete a foros y busca eventos.",
        "tool.recipes.desc": "Recetario comunitario para cocinar tus platos latinos favoritos.",
        "tool.open": "Abrir",
        "nav.budgeter": "Presupuesto",
        "nav.career": "Centro de Carrera",
        "btn.visit": "Visitar Sitio Oficial",
        "lbl.backTo": "Volver a",
        "lbl.gettingThere": "Cómo llegar",
        "lbl.highlights": "Destacados",
        "lbl.offices": "Ubicación de Oficinas",
        "lbl.expiry": "Fecha de Vencimiento",
        "lbl.reminder": "Recordatorio de Renovación",
        "lbl.completeRoute": "Marcar como Completada",
        "lbl.completed": "¡Completada!",
        "lbl.badges": "Medallas",
        "lbl.trainWithMe": "Entrena Conmigo",
        "lbl.collectiveGoal": "Meta Colectiva",
        "hero.greeting": "Hola,",
        "hero.subtitle": "¿Listo para explorar?",
        "challenge.title": "Reto del Día",
        "challenge.name": "Paseo y Reflexión",
        "challenge.desc": "Encuentra un lugar tranquilo en St. Stephen's Green y dedica 10 minutos a observar tu entorno.",
        "btn.startNow": "Empezar Ahora",
        "common.viewAll": "Ver todos",
        "cat.body": "Cuerpo",
        "cat.explore": "Explorar",
        "cat.wellness": "Bienestar",
        "cat.social": "Social",
        "cat.admin": "Trámites",
        "cat.extras": "Extras",
        "home.quickAccess": "Acceso Rápido",
        "nav.lang": "Idioma",
        "nav.lang_name": "Español",
        "nav.lang_toggle": "English",
        "event.title": "Próximos Eventos",
        "event.subtitle": "Encuentros gratuitos y comunitarios.",
        "event.free": "Entrada Gratis",
        "event.viewFull": "Ver Calendario Completo",
        "forum.title": "Foro de la Comunidad",
        "forum.subtitle": "Haz preguntas, comparte consejos.",
        "forum.likes": "Me gusta",
        "forum.replies": "Respuestas",
        "forum.placeholder": "Pregunta algo...",
        "weather.good": "Perfecto para un paseo",
        "weather.bad": "Actividad en Interior Recomendada",
        "weather.clear": "Despejada",
        "weather.cloudy": "Parcialmente Nublado",
        "weather.rain": "Lloviendo",
        "weather.storm": "Tormenta",
        "weather.fog": "Niebla",
        "roadmap.title": "Hoja de Ruta",
        "roadmap.subtitle": "Pasos esenciales para tus primeras semanas",
        "search.placeholder": "Buscar recursos en Dublín...",
        "search.popular": "Palabras Clave",
        "search.results": "Resultados",
        "search.noResults": "No se encontraron resultados...",
        "exercise.title": "Fitness Universal",
        "exercise.subtitle": "Rutas y actividades adaptativas para todos. Elige una categoría para empezar a explorar.",
        "exercise.cat.parks.title": "Circuitos de Caminata en Parques",
        "exercise.cat.parks.desc": "Directorio de rutas de caminata en los mejores parques de Dublín (Phoenix, St. Anne's, Fairview, etc.).",
        "exercise.cat.swimming.title": "Natación en Aguas Abiertas",
        "exercise.cat.swimming.desc": "Directorio de lugares para nadar en el mar (Seapoint, Forty Foot, Vico, etc.).",
        "exercise.cat.cycling.title": "Rutas de Ciclismo",
        "exercise.cat.cycling.desc": "Ciclovías seguras y vías verdes (Clontarf, Phoenix Park, Canales).",
        "exercise.cat.gyms.title": "Gimnasios Públicos y Piscinas",
        "exercise.cat.gyms.desc": "Centros de ocio asequibles y de alta calidad gestionados por el Ayuntamiento de Dublín.",
        "exercise.cat.physio.title": "Fisioterapia y Recuperación",
        "exercise.cat.physio.desc": "Encuentra fisioterapeutas comunitarios y clínicas.",
        "exercise.cat.run.title": "Carrera Costera de Dublín",
        "exercise.cat.run.desc": "Ruta escénica de 5km por la costa. Disfruta la brisa marina y terreno plano.",
        "exercise.cat.walk.title": "Paseo del Río Liffey",
        "exercise.cat.walk.desc": "Un bucle suave de 2km a lo largo del Río Liffey. Perfecto para principiantes o rehabilitación.",
        "exercise.cat.teams.title": "Equipos Deportivos Comunitarios",
        "exercise.cat.teams.desc": "Únete a equipos amateur gratuitos de fútbol, rugby o GAA en parques como Fairview.",
        "comm.title": "Comunidad",
        "comm.subtitle": "El corazón de immiGrow. Conecta y crece junto a otros.",
        "comm.myStory": "Mi Historia",
        "comm.myStory.desc": "Personaliza tu perfil, cuenta tu historia y conecta con otros.",
        "comm.circles": "Círculos",
        "comm.circles.desc": "Grupos de apoyo para mujeres, latinos, nuevos migrantes y más.",
        "comm.mentors": "Mentores",
        "comm.mentors.desc": "Conecta con migrantes experimentados que pueden guiarte.",
        "comm.events": "Eventos",
        "comm.events.desc": "Encuentros presenciales, caminatas y cafés para socializar.",
        "comm.socialFit": "Social Fitness",
        "comm.socialFit.desc": "Entrena con otros, únete a retos y comparte tus logros.",
        "comm.identity": "Tu Identidad",
        "comm.namePlaceholder": "Tu nombre o apodo...",
        "vault.subtitle": "Tu centro personal de inmigración. Categorías, notas y recordatorios para tu vida en Irlanda.",
        "vault.quickNotes": "Notas de Copia Rápida",
        "vault.addNote": "+ Nueva Nota",
        "vault.saveNote": "Guardar Nota",
        "vault.myDocs": "Mis Documentos",
        "vault.newDoc": "+ Nuevo Doc",
        "vault.docName": "Nombre del Documento",
        "vault.category": "Categoría",
        "vault.reminderOn": "Aviso Activado",
        "vault.remove": "Borrar",
        "vault.createRecord": "Crear Registro",
        "vault.cat.identity": "Identidad",
        "vault.cat.housing": "Vivienda",
        "vault.cat.health": "Salud",
        "vault.cat.work": "Trabajo",
        "vault.content": "Contenido",
        "vault.label": "Etiqueta (ej: PPSN)",
        "safe.title": "Seguridad",
        "safe.disclaimer": "immiGrow es informativo. ¡Cuídate!",
        "safe.public": "Lugares Públicos",
        "safe.public.desc": "Queda siempre en lugares concurridos y bien iluminados, como cafés o parques principales.",
        "safe.inform": "Avisa a Terceros",
        "safe.inform.desc": "Informa a un amigo o familiar sobre a dónde vas y con quién te vas a encontrar.",
        "safe.privacy": "Cuida tu Privacidad",
        "safe.privacy.desc": "No compartas datos sensibles como tu cuenta bancaria o dirección exacta de inmediato.",
        "safe.instinct": "Confía en tu Instinto",
        "safe.instinct.desc": "Si algo no se siente bien, está bien irse o cancelar. Tu seguridad es lo primero.",
        "jobs.title": "Listo para Dublín",
        "mental.subtitle": "Recursos y apoyo para tu bienestar emocional.",
        "mental.professionals": "Directorio de Profesionales",
        "mental.crisis.title": "¿Necesitas ayuda ahora?",
        "mental.crisis.desc": "Apoyo confidencial 24/7 a un texto o llamada de distancia.",
        "mental.crisis.btn": "Llama 116 123",
        "mental.support_lang": "Apoyo en tu idioma",
        "mental.guides": "Guías y Recursos",
        "women.subtitle": "Recursos específicos y guías de atención para la salud de la mujer en Irlanda.",
        "procedures.subtitle": "Guías esenciales para tus procesos migratorios y administrativos en Irlanda.",
        "diff.easy": "Fácil",
        "diff.medium": "Medio",
        "diff.hard": "Difícil",
    },
    pt: {
        "nav.home": "Início",
        "nav.tourism": "Turismo Ativo",
        "nav.parks": "Parques",
        "nav.swimming": "Natação",
        "nav.cycling": "Ciclismo",
        "nav.mental": "Saúde Mental",
        "nav.women": "Saúde da Mulher",
        "nav.procedures": "Processos",
        "nav.community": "Comunidade",
        "nav.vault": "Meu Cofre",
        "nav.achievements": "Conquistas",
        "nav.socialFit": "Fitness Social",
        "nav.sportsTeams": "Equipes Esportivas",
        "nav.recipes": "Sabores de Casa",
        "nav.more": "Mais",
        "nav.physical_activity": "Atividade",
        "nav.health": "Saúde",
        "nav.admin": "Recursos",
        "nav.physiotherapy": "Fisio",
        "nav.calculator": "Calculadora",
        "nav.jobs": "Pronto para Dublin",
        "nav.slang": "Fale como um Local",
        "nav.active": "Rotas Ativas",
        "nav.toolkit": "Caixa de Ferramentas",
        "toolkit.title": "Central de Essenciais",
        "toolkit.subtitle": "Ferramentas essenciais para sua vida em Dublin.",
        "tool.vault.desc": "Armazenamento privado para seus prazos e documentos.",
        "tool.budgeter.desc": "Planeje suas finanças com médias locais de Dublin.",
        "tool.career.desc": "Guias para encontrar trabalho e dicas de currículo.",
        "tool.slang.desc": "Aprenda gírias essenciais para soar como um local.",
        "tool.achievements.desc": "Acompanhe seu progresso e ganhe medalhas.",
        "tool.community.desc": "Conecte-se com outros migrantes, participe de fóruns e eventos.",
        "tool.recipes.desc": "Livro de receitas comunitário para cozinhar seus pratos favoritos.",
        "tool.open": "Abrir",
        "nav.budgeter": "Orçamento",
        "nav.career": "Centro de Carreira",
        "btn.visit": "Visitar Site Oficial",
        "lbl.backTo": "Voltar para",
        "lbl.gettingThere": "Como chegar",
        "lbl.highlights": "Destaques",
        "lbl.offices": "Localização",
        "lbl.expiry": "Data de Expiração",
        "lbl.reminder": "Lembrete de Renovação",
        "lbl.completeRoute": "Marcar como Concluída",
        "lbl.completed": "Concluído!",
        "lbl.badges": "Medalhas",
        "lbl.trainWithMe": "Treine Comigo",
        "lbl.collectiveGoal": "Meta Colectiva",
        "hero.greeting": "Olá,",
        "hero.subtitle": "Pronto para explorar?",
        "challenge.title": "Desafio do Dia",
        "challenge.name": "Passeio e Reflexão",
        "challenge.desc": "Encontre um lugar calmo no St. Stephen's Green e tire 10 minutos para observar seu redor.",
        "btn.startNow": "Começar Agora",
        "common.viewAll": "Ver todos",
        "cat.body": "Corpo",
        "cat.explore": "Explorar",
        "cat.wellness": "Bem-estar",
        "cat.social": "Social",
        "cat.admin": "Processos",
        "cat.extras": "Extras",
        "home.quickAccess": "Acesso Rápido",
        "nav.lang": "Idioma",
        "nav.lang_name": "Português",
        "nav.lang_toggle": "Español",
        "event.title": "Próximos Eventos",
        "event.subtitle": "Encontros gratuitos e comunitários.",
        "event.free": "Entrada Grátis",
        "event.viewFull": "Ver Calendário Completo",
        "forum.title": "Fórum da Comunidade",
        "forum.subtitle": "Tire dúvidas, compartilhe dicas.",
        "forum.likes": "Curtidas",
        "forum.replies": "Respostas",
        "forum.placeholder": "Pergunte algo...",
        "weather.good": "Perfeito para um passeio",
        "weather.bad": "Atividade Interna Recomendada",
        "weather.clear": "Céu Limpo",
        "weather.cloudy": "Parcialmente Nublado",
        "weather.rain": "Chovendo",
        "weather.storm": "Tempestade",
        "weather.fog": "Neblina",
        "roadmap.title": "Guia do Recém-Chegado",
        "roadmap.subtitle": "Passos essenciais para suas primeiras semanas",
        "search.placeholder": "Buscar recursos em Dublin...",
        "search.popular": "Palavras-chave",
        "search.results": "Resultados",
        "search.noResults": "Nenhum resultado encontrado...",
        "exercise.title": "Fitness Universal",
        "exercise.subtitle": "Rotas e atividades adaptáveis para todos. Escolha uma categoria para começar.",
        "exercise.cat.parks.title": "Circuitos em Parques",
        "exercise.cat.parks.desc": "Diretório de rotas nos melhores parques de Dublin (Phoenix, St. Anne's, Fairview, etc.).",
        "exercise.cat.swimming.title": "Natação em Mar Aberto",
        "exercise.cat.swimming.desc": "Diretório de pontos de natação no mar (Seapoint, Forty Foot, Vico, etc.).",
        "exercise.cat.cycling.title": "Rotas de Ciclismo",
        "exercise.cat.cycling.desc": "Ciclovias seguras e vias verdes (Clontarf, Phoenix Park, Canais).",
        "exercise.cat.gyms.title": "Ginasios Públicos e Piscinas",
        "exercise.cat.gyms.desc": "Centros de lazer acessíveis e de alta qualidade geridos pela Prefeitura.",
        "exercise.cat.physio.title": "Fisioterapia e Recuperação",
        "exercise.cat.physio.desc": "Encontre fisioterapeutas comunitários e clínicas.",
        "exercise.cat.run.title": "Corrida Costeira de Dublin",
        "exercise.cat.run.desc": "Rota cênica de 5km pela costa. Aproveite a brisa do mar e terreno plano.",
        "exercise.cat.walk.title": "Passeio pelo Rio Liffey",
        "exercise.cat.walk.desc": "Um circuito suave de 2km ao longo do Rio Liffey. Perfeito para iniciantes.",
        "exercise.cat.teams.title": "Times Esportivos Comunitários",
        "exercise.cat.teams.desc": "Participe de times amadores gratuitos de Futebol, Rugby ou GAA em parques locais.",
        "comm.title": "Comunidade",
        "comm.subtitle": "O coração do immiGrow. Conecte-se e cresça com os outros.",
        "comm.myStory": "Minha História",
        "comm.myStory.desc": "Personalize seu perfil, conte sua história e conecte-se com outros.",
        "comm.circles": "Círculos",
        "comm.circles.desc": "Grupos de apoio para mulheres, latinos, recém-chegados e mais.",
        "comm.mentors": "Mentores",
        "comm.mentors.desc": "Conecte-se com migrantes experientes que podem guiá-lo.",
        "comm.events": "Eventos",
        "comm.events.desc": "Encontros presenciais, caminhadas e café para socializar.",
        "comm.socialFit": "Fitness Social",
        "comm.socialFit.desc": "Treine com outros, participe de desafios e compartilhe conquistas.",
        "comm.identity": "Sua Identidade",
        "comm.namePlaceholder": "Seu nome ou apelido...",
        "vault.subtitle": "Seu centro pessoal de imigração. Categorias, notas e lembretes para sua vida na Irlanda.",
        "vault.quickNotes": "Notas de Cópia Rápida",
        "vault.addNote": "+ Nova Nota",
        "vault.saveNote": "Salvar Nota",
        "vault.myDocs": "Meus Documentos",
        "vault.newDoc": "+ Novo Doc",
        "vault.docName": "Nome do Documento",
        "vault.category": "Categoria",
        "vault.reminderOn": "Lembrete Ativado",
        "vault.remove": "Remover",
        "vault.createRecord": "Criar Registro",
        "vault.cat.identity": "Identidade",
        "vault.cat.housing": "Habitação",
        "vault.cat.health": "Saúde",
        "vault.cat.work": "Trabalho",
        "vault.content": "Conteúdo",
        "vault.label": "Etiqueta (ex: PPSN)",
        "safe.title": "Segurança",
        "safe.disclaimer": "immiGrow é informativo. Cuide-se!",
        "safe.public": "Locais Públicos",
        "safe.public.desc": "Sempre se encontre em áreas públicas movimentadas e bem iluminadas, como cafés ou parques principais.",
        "safe.inform": "Informe Alguém",
        "safe.inform.desc": "Avise um amigo ou familiar sobre para onde você está indo e com quem vai se encontrar.",
        "safe.privacy": "Proteja sua Privacidade",
        "safe.privacy.desc": "Não compartilhe detalhes confidenciais, como sua conta bancária ou endereço residencial, imediatamente.",
        "safe.instinct": "Confie no seu Instinto",
        "safe.instinct.desc": "Se algo parecer errado, tudo bem ir embora ou cancelar. Sua segurança vem em primeiro lugar.",
        "jobs.title": "Pronto para Dublin",
        "mental.subtitle": "Recursos e apoio para o seu bem-estar emocional.",
        "mental.professionals": "Diretório de Profissionais",
        "mental.crisis.title": "Precisa de ajuda agora?",
        "mental.crisis.desc": "Apoio confidencial 24/7 a apenas uma mensagem ou ligação.",
        "mental.crisis.btn": "Ligue 116 123",
        "mental.support_lang": "Apoio no seu idioma",
        "mental.guides": "Guias e Recursos",
        "women.subtitle": "Recursos específicos e guias de cuidados para a saúde da mulher na Irlanda.",
        "procedures.subtitle": "Guias essenciais para seus processos imigratórios e administrativos na Irlanda.",
        "jobs.subtitle": "Seu guia para encontrar trabalho e construir carreira na Irlanda.",
        "jobs.training": "Treinamento e Educação",
        "jobs.sb.desc": "Cursos de ensino superior gratuitos ou altamente subsidiados.",
        "jobs.solas.desc": "Autoridade de Educação e Treinamento Profissional na Irlanda.",
        "tourism.subtitle": "Explore Dublin e arredores. Trilhas, caminhadas e pontos turísticos.",
        "diff.easy": "Fácil",
        "diff.medium": "Médio",
        "diff.hard": "Difícil",
    }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [language, setLanguage] = useState<Language>("en");
    const [userName, setUserNameState] = useState<string>("");

    useEffect(() => {
        const savedLang = localStorage.getItem('iGrow_lang') as Language;
        if (savedLang) setLanguage(savedLang);

        const savedName = localStorage.getItem('iGrow_user');
        if (savedName) setUserNameState(savedName || "");
    }, []);

    const setUserName = (name: string) => {
        setUserNameState(name);
        localStorage.setItem('iGrow_user', name);
    };

    const changeLanguage = (newLang: Language) => {
        setLanguage(newLang);
        localStorage.setItem('iGrow_lang', newLang);
    };

    const toggleLanguage = () => {
        setLanguage((prev) => {
            let newLang: Language;
            if (prev === "en") newLang = "pt";
            else if (prev === "pt") newLang = "es";
            else newLang = "en";

            localStorage.setItem('iGrow_lang', newLang);
            return newLang;
        });
    };

    const t = (key: string) => {
        const dict = dictionaries[language] as Record<string, string>;
        return dict[key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage: changeLanguage, toggleLanguage, t, userName, setUserName }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error("useLanguage must be used within a LanguageProvider");
    }
    return context;
}
